mybatis:
  type-aliases-package: com.chinaredstar.jedi.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rh?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  rabbitmq:
    host: mq201.dev.rs.com
    port: 5672
    username: dev
    password: dev_user
    virtual-host: /

